### ISSUE TITLE
Will not launch for me with Python 3.13 (macOS)

### ISSUE THREAD

**Issue by dgatwood** [CensoredUsername/unrpyc#255]
At least with the homebrew build of python 3.13 on macOS, this script fails to run (at least with all of the open pull requests merged in, which is necessary to make it usable).  It works correctly with the 3.9 build.  With 3.13, I just get

```
Traceback (most recent call last):
  File "/Users/dg/unrpyc3/unrpyc/unrpyc.py", line 48, in <module>
    import decompiler
  File "/Users/dg/unrpyc3/unrpyc/decompiler/__init__.py", line 24, in <module>
    from .renpycompat import renpy
  File "/Users/dg/unrpyc3/unrpyc/decompiler/renpycompat.py", line 26, in <module>
    magic.fake_package("renpy")
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/dg/unrpyc3/unrpyc/decompiler/magic.py", line 665, in fake_package
    return __import__(name)
ModuleNotFoundError: No module named 'renpy'
```

I've also tried symlinking renpy from the renpy SDK into the script's working directory, and it fails with

```
Traceback (most recent call last):
  File "/Users/dg/unrpyc3/unrpyc/unrpyc.py", line 48, in <module>
    import decompiler
  File "/Users/dg/unrpyc3/unrpyc/decompiler/__init__.py", line 29, in <module>
    from . import sl2decompiler
  File "/Users/dg/unrpyc3/unrpyc/decompiler/sl2decompiler.py", line 27, in <module>
    from . import atldecompiler
  File "/Users/dg/unrpyc3/unrpyc/decompiler/atldecompiler.py", line 30, in <module>
    class ATLDecompiler(DecompilerBase):
    ...<191 lines>...
            self.write(f'time {ast.time}')
  File "/Users/dg/unrpyc3/unrpyc/decompiler/atldecompiler.py", line 84, in ATLDecompiler
    @dispatch(renpy.atl.RawMultipurpose)
              ^^^^^^^^^
AttributeError: module 'renpy' has no attribute 'atl'
```

No idea how to resolve.  Rolling back to 3.9 fixes the issue, and no idea why.

**Comment by dgatwood** [comment]
Sorry for the late response.  It fails with 3.13 (as installed from homebrew) reliably, without regard to the input file, or even with no input files provided.

Not sure how much info I can give to help out other than steps to repro:

- Install homebrew on macOS.
- Install Python 3.13
- Grab from top-of-tree (11de7c063de710ae30dbc7f190013ce2c88af6cc)
- Run "python3.13 /path/to/unrpyc3/unrpyc/unrpyc.py"

**Comment by dgatwood** [comment]
Laughing now.  I was misled by github saying nothing had changed since 2024.  I just pulled, and the bug appears to be fixed.

**Comment by madeddy** [comment]
Happens. If it works now, good for you! 
Greets
